security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Infrastructure\Security\IdentityUser: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        identity_provider:
            id: App\Infrastructure\Security\IdentityUserProvider

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: identity_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: dashboard_index
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/collect/, roles: PUBLIC_ACCESS }
        - { path: ^/api/event, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            App\Infrastructure\Security\IdentityUser:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
